# This file was generated by GoReleaser. DO NOT EDIT.
cask "html2md" do
  name "html2md"
  desc "Convert HTML pages to Markdown from the command line"
  homepage "https://github.com/vsyaco/html2md"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "html2md"

  on_macos do
    on_intel do
      url "https://github.com/vsyaco/html2md/releases/download/v#{version}/html2md_darwin_amd64.tar.gz"
      sha256 "6fb5fb8e3ac252dea3ce2c934bd4451bbc5f917fcfb669fee43284fd4e7effc6"
    end
    on_arm do
      url "https://github.com/vsyaco/html2md/releases/download/v#{version}/html2md_darwin_arm64.tar.gz"
      sha256 "00aaab36f62ca3e93ba01a151173898502393ba7e6322d86b9fa646c54aa1b3f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/vsyaco/html2md/releases/download/v#{version}/html2md_linux_amd64.tar.gz"
      sha256 "a9f7917a874da00ebc485311851f0a15e60d3f0ae11574db3a96f59e8ec3d045"
    end
    on_arm do
      url "https://github.com/vsyaco/html2md/releases/download/v#{version}/html2md_linux_arm64.tar.gz"
      sha256 "0f6da1ef93328565d21e1a2672b9f1762629f839212742bfa0b4107c4d055f60"
    end
  end

  # No zap stanza required
end
